sudo: required

language: generic

services:
  - docker

before_install:
  - docker build --build-arg GH_TOKEN=$GH_TOKEN --build-arg REPO=$REPO -t moussavdb/data-yildiz_online_client:latest -t moussavdb/data-yildiz_online_client:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/data-yildiz_online_client
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/data-yildiz_online_client:latest;
    docker push moussavdb/data-yildiz_online_client:build_$TRAVIS_BUILD_NUMBER;
